"""empty message

Revision ID: 5de3bb0a6754
Revises: a80efd282c26
Create Date: 2021-05-10 15:33:40.379975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5de3bb0a6754'
down_revision = 'a80efd282c26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_lastName_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_lastName_key', 'users', ['lastName'])
    # ### end Alembic commands ###
